### ISSUE TITLE
Might have a look at updating to Electron 5

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-electron#1]
Just want to say that I might have a look at this during the summer.

**Comment by cmeeren** [comment]
Ok, I have seemingly working bindings for Electron 5 now. In other words, I'd like to take over this repo. :)

I started with ts2fable and have made several passes through the bindings to fix a lot of small stuff. I have yet to comb systematically through the full Electron API docs and make sure everything makes sense (and fix the broken function documentation, which was broken even in the TS file), but I'd say the bindings are more or less fully usable already. There might be some further breaking changes as I go through everything and make adjustments, but I can't promise I'll be able to do that right now (I'm getting married in a week), so I think a prerelease on nuget is a good course of action now. (I should probably be able to do it during the summer, if not earlier.)

Please let me know if there is anything I should know regarding common (or just useful) tooling/practices when it comes to releasing bindings. (I usually release nugets automatically through CI, triggered by git tags.)

**Comment by alfonsogarciacaro** [comment]
That's great @cmeeren! Could you please send a PR for the update? Then we can give you write access to the repo :+1:

We don't have yet specific guidelines for bindings. Some are "purer", in the sense they only translate the Typescript declarations, and others may add a thin layer to make interaction with the library more idiomatic from F# (e.g. like Fable.React does). About the versions, for now please include the Electron version you're targeting in the README/documentation.
