### ISSUE TITLE
WebView

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable-electron#2]
I'm trying to figure out how to use the `WebViewElement` functionality to create a `webview` from F#.

Ideally I'd like to do this in react style. I've found a [react wrapper for Electron](https://github.com/keokilee/react-electron-webview) but I'm not sure how to import it to achieve this functionality. I've worked successfully with the fable-react samples.

Right now I'm putting the `<webview>` in html and ignoring it in my render code.

**Comment by alfonsogarciacaro** [comment]
Hi @aolney! Looking at the [Webview sample](https://github.com/keokilee/react-electron-webview/blob/master/test/webview.js#L11) it seems you need to import the default member of "webview", so something like this should work:

```fsharp
open Fable.Core.JsInterop
let WebView = importDefault<obj> "react-electron-webview"
```

Then you can use `Fable.Helpers.React.from WebView` to create a React component as in the [material-ui sample](https://github.com/fable-compiler/fable-electron/blob/master/samples/material-ui/src/renderer.fsx#L54).

I hope this helps!

**Comment by aolney** [comment]
You are legend, thanks!

**Comment by alfonsogarciacaro** [comment]
Ups, sorry! Actually you have to import the webview as a `React.ComponentClass`. I edited my code above ☝️

Please tell me if you need help for anything else. And when finishing your project, sharing the code or writing a post about your experience is much appreciated! 😄

**Comment by aolney** [comment]
The above worked but I'm stuck on a related issue. The `webview` does not want to expand to fill its enclosing `div`. I can edit `height` in the running page through developer tools and that solves the problem, but I'm unable to set the height in code. If I do this:

```
R.div [ Style [ GridArea "2 / 1 / 2 / 1"; CSSProp.Width (U2.Case2 "100%"); CSSProp.Height (U2.Case2 "100%");  ] ] [
      
            R.from WebView
                !!["src" => "http://stackoverflow.com/questions/21103622/auto-resize-image-in-css-flexbox-layout-and-keeping-aspect-ratio";
                     "style" => "height: 100%;";
                  ][]
    ]
```
it compiles but runs with an empty page (root div is never replaced).

If I replace `"style" => "height: 100%;";` with `"height" => "100%";` then I get a `height` property in the dom but it is not part of a style element so nothing happens.

Could you please explain how to add CSS properties when using the `R.from` construct?

BTW [I modified your electron hello world example by including vscode debugging and a webpack watch task](https://github.com/aolney/fable-electron-vscode-debug-helloworld)

**Comment by alfonsogarciacaro** [comment]
Nice, thanks for extending the sample! :+1:

Sorry, I don't know exactly how this WebView component works so I cannot tell for sure. Maybe you can put the CSSProp list directly in the props object passed to WebView?

```fsharp
R.from WebView !![
    "src" => "http://stackoverflow.com/questions/21103622/auto-resize-image-in-css-flexbox-layout-and-keeping-aspect-ratio";
    "style" => [CSSProp.Height "100%"]
][]
```

If this doesn't work, could you post the JS you want to generate? Cheers!

**Comment by aolney** [comment]
Brilliant!
