### ISSUE TITLE
DevTools don't open with new bindings

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/fable-electron#3]
Hi, I appreciate the work you're doing on this. When trying to update to use these bindings from your older ones in the material ui demo you made it seems to all compile correctly but when doing the webpack dev target it all compiles but never launches the application. Doing the other modes everything works fine. Downgrading to electron 5 fixed this issue.

**Comment by cmeeren** [comment]
Thanks! I have the same problem but don't know what causes it. It works with 6.0.0-beta-13 and below. It's probably not the bindings, but I have no idea what it is. Do you have any idea?

By the way, I will publish these bindings and update the demo once I get this working.

**Comment by cmeeren** [comment]
It seems to be an issue with electron-webpack: https://github.com/electron-userland/electron-webpack/issues/308

**Comment by cmeeren** [comment]
Actually, it seems like it's an Electron bug: electron/electron#19468

**Comment by Shmew** [comment]
How incredibly odd, thanks for letting me know!
