### ISSUE TITLE
Dynamic vs. Foreign Interfaces with Electron

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable-electron#4]
In trying to port the webGLTerrain sample to Electron, I find that the dynamic method of interacting with js works but the foreign interface method does not. I wonder if this is a limitation of Fable or if I'm doing something wrong (probably).

I'm specifically working with the `ImprovedNoise.js` which I've put in `apps/js`. `ImprovedNoise` is a function (`unit -> obj`) that returns an object with a single available function `noise` (`x:float * y:float * z:float -> float`).

The [original sample uses requirejs in its `index.html`](https://github.com/fable-compiler/Fable/blob/master/samples/browser/webGLTerrain/index.html) which seems to put things in a global scope.

My `index.html` has just one script `<script src="js/renderer.js"></script>`

I had a problem getting any exported function out of `ImprovedNoise.js`, so I changed the first line from `var ImprovedNoise = function () {` to  `exports.ImprovedNoise = function () {`

So with that change, I can get the dynamic approach to work as below.

**Dynamic (working)**
`renderer.fsx` is

```
#r "../node_modules/fable-core/Fable.Core.dll"
#load "../node_modules/fable-import-three/Fable.Import.Three.fs"

open Fable.Import
open System
open Fable.Core
open Fable.Core.JsInterop

let ImprovedNoise = importMember<unit->obj>("../app/js/ImprovedNoise.js")
let noise = ImprovedNoise() //call the function; now we have an object containing the function we want
let output = noise?noise$(1.4,2.3,3.6) //call the function
Browser.console.log(output);
```

The emitted js is 

```
/***/ function(module, exports, __webpack_require__) {

	"use strict";
	
	exports.__esModule = true;
	exports.output = exports.noise = exports.t = exports.ImprovedNoise = undefined;
	
	var _ImprovedNoise = __webpack_require__(2);
	
	var ImprovedNoise = exports.ImprovedNoise = _ImprovedNoise.ImprovedNoise;
	var t = exports.t = 1 + 1;
	console.log(t);
	var noise = exports.noise = ImprovedNoise();
	console.log(t);
	var output = exports.output = noise.noise(1.4, 2.3, 3.6);
	console.log(output);


/***/ },
/* 1 */,
/* 2 */
/***/ function(module, exports) {

	// http://mrl.nyu.edu/~perlin/noise/
	
	exports.ImprovedNoise = function () {
```
As can be seen, `_ImprovedNoise.ImprovedNoise;` makes the function accessible.

**Foreign Interface (not working)**
Using the same approach as in this sample originally, I found that the `ImprovedNoise.js` code was not being brought in by webpack at all. So I used `importDefault` as below, not binding the result to anything, as was suggested in [this sample](https://github.com/fable-compiler/fable-electron/blob/ee76face7cb4fd9d5a93459eea9e33bda5256d49/samples/react-todomvc/src/renderer.fsx)

Unfortunately, while it gets the function in the right place in `renderer.js`, it isn't wired up in a way that makes it usable.

```
#r "../node_modules/fable-core/Fable.Core.dll"
#load "../node_modules/fable-import-three/Fable.Import.Three.fs"

open Fable.Import
open System
open Fable.Core
open Fable.Core.JsInterop

/// Represents the API exposed by ImprovedNoise script
type IPerlin =
    abstract noise: x:float * y:float * z:float -> float

[<Global>]
let ImprovedNoise(): IPerlin = jsNative

importDefault("../app/js/ImprovedNoise.js") //to attach the js via webpack

let perlin = ImprovedNoise()
let output = perlin.noise(1.4,2.3,3.6) 
Browser.console.log(output);
```
The emitted js:

```
/***/ function(module, exports, __webpack_require__) {

	"use strict";
	
	exports.__esModule = true;
	exports.output = exports.perlin = exports.t = undefined;
	
	var _ImprovedNoise = __webpack_require__(2);
	
	var _ImprovedNoise2 = _interopRequireDefault(_ImprovedNoise);
	
	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
	
	_ImprovedNoise2.default;
	var t = exports.t = 1 + 1;
	console.log(t);
	var perlin = exports.perlin = ImprovedNoise();
	console.log(t);
	var output = exports.output = perlin.noise(1.4, 2.3, 3.6);
	console.log(output);


/***/ },
/* 1 */,
/* 2 */
/***/ function(module, exports) {

	// http://mrl.nyu.edu/~perlin/noise/
	
	exports.ImprovedNoise = function () {
	
```

As you can see, there is an `ImprovedNoise()` function that is not wired up to the function in `ImprovedNoise.js`

Is there a way to make this connect up? It seems that foreign interfaces work in electron when distributed as node modules (many examples of this), so I'd think there would be a way of making it work here. I'm a newb on pretty much everything js, so the answer is not obvious to me.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed summary. I understand it can be confusing to work with the different import methods, I need to work on the documentation for that.

My recommendation is that in this simple case you combine both. The only interesting part is the `IPerlin` interface, so you can define that and still use the import expression:

```fsharp
type IPerlin =
    abstract noise: x:float * y:float * z:float -> float

let ImprovedNoise = importMember<unit->IPerlin>("../app/js/ImprovedNoise.js")

let perlin = ImprovedNoise()
let output = perlin.noise(1.4,2.3,3.6) 
Browser.console.log(output);
```

You can also use the `ImportAttribute` but this is only recommended for auto-generated bindings.

```fsharp
type IPerlin =
    abstract noise: x:float * y:float * z:float -> float


[<Import("ImprovedNoise", "../app/js/ImprovedNoise.js">]
let ImprovedNoise(): IPerlin = jsNative

let perlin = ImprovedNoise()
let output = perlin.noise(1.4,2.3,3.6) 
Browser.console.log(output);
```

Both of these should work :)

> Note the way relative import paths are resolved will change in 0.7 (hopefully) for the better. I'll write a blog post about that.

**Comment by aolney** [comment]
Thanks :) Hope to have a new sample done this weekend

**Comment by aolney** [comment]
Based on your comments, I had hoped the following would work for `FirstPersonControls`

```
type IFirstPersonControls =
    abstract movementSpeed: float with get, set
    abstract lookSpeed: float with get, set
    abstract handleResize: unit -> unit
    abstract update: float -> unit

[<Import("FirstPersonControls", "../app/js/FirstPersonControls.js")>]
[<Emit("new FirstPersonControls($0...)")>]
let FirstPersonControls(camera: Three.Camera,
                        domElement: Browser.HTMLElement):
                        IFirstPersonControls = jsNative
```

However, the two attributes in sequence seem to interfere with each other.

Instead I ended up with this (this works):

```
type IFirstPersonControls =
    abstract movementSpeed: float with get, set
    abstract lookSpeed: float with get, set
    abstract handleResize: unit -> unit
    abstract update: float -> unit

let FirstPersonControls : Three.Camera->Browser.HTMLElement -> IFirstPersonControls  = importMember<Three.Camera->Browser.HTMLElement -> IFirstPersonControls>("../app/js/FirstPersonControls.js") 

[<Emit("new FirstPersonControls($0...)")>]
let New_FirstPersonControls(a,b)=  FirstPersonControls a b
```
It was necessary to split this up because I could not `importMember` and `Emit` at the same time -- `Emit` would cause the import to fail.

Also if I do not convert the signature and leave as tuple, e.g.

```
let FirstPersonControls : Three.Camera*Browser.HTMLElement -> IFirstPersonControls  = importMember<Three.Camera*Browser.HTMLElement -> IFirstPersonControls>("../app/js/FirstPersonControls.js") 

[<Emit("new FirstPersonControls($0...)")>]
let New_FirstPersonControls =  FirstPersonControls
```
Then the emitted js (of interest) is 
```
var controls = function (tupledArg) {
	        return new FirstPersonControls()([tupledArg[0], tupledArg[1]]);
	    }([camera, domElement]);
```
I can improve this by making all later calls dynamic with destructure, e.g:
```
    let controls = New_FirstPersonControls$(camera :> Three.Camera, domElement)
    controls?movementSpeed <- 1000.0
    controls?lookSpeed <- 0.1
```
in which case the emitted js becomes
```
var controls = new FirstPersonControls()(camera, domElement);
```
which is closer but still not right.

Though I'm managed to find a way to make this work, I wonder if there's a more idiomatic way?

**Comment by alfonsogarciacaro** [comment]
Interesting, you're not the first person who applies `Import` and `Emit` attributes at the same time. It didn't occur to me that users would try to do that :wink:

We're still polishing the ways to interact with JS code. The Three.js sample was done at the beginning when Fable had limited dynamic programming capabilities and there were no import expressions. Now I'd try to avoid the attributes whenever possible. Your example could work as follows:

```fsharp
open System

type IFirstPersonControls =
    abstract movementSpeed: float with get, set
    abstract lookSpeed: float with get, set
    abstract handleResize: unit -> unit
    abstract update: float -> unit

let FirstPersonControls : Func<Three.Camera, Browser.HTMLElement, IFirstPersonControls> =
    importMember "../app/js/FirstPersonControls.js"

let controls = FirstPersonControls.Invoke(camera :> Three.Camera, domElement)
controls.movementSpeed <- 1000.0
controls.lookSpeed <- 0.1
```

`FirstPersonControls` must be a delegate (`System.Func<>`) to prevent the F# compiler from currying the arguments. I know this is confusing and I tried to make this as transparent as possible to the user. For example, arguments won't be transformed into a tuple when using dynamic programming ([see docs](http://fable.io/docs/interacting.html#Calling-F-code-from-JavaScript)):

```
let FirstPersonControls : obj = importMember "../app/js/FirstPersonControls.js"

let controls =
    FirstPersonControls$(camera :> Three.Camera, domElement)
    |> unbox< IFirstPersonControls >
```

Unfortunately, this won't be the case if you explicitly set the signature of the function: `'a->'b->'c` means arguments are curried, and `'a * 'b->'c` means argument are a tuple. So you must use `Func<'a,'b,'c>` to apply arguments _normally_.

**Comment by aolney** [comment]
Thanks :smile: However your example does not include `new`

I used your boxing trick to modify it to this:
```
let FirstPersonControls : Three.Camera*Browser.HTMLElement -> IFirstPersonControls  =
    importMember "../app/js/FirstPersonControls.js"
....
let controls = createNew  FirstPersonControls (camera :> Three.Camera, domElement) |> unbox< IFirstPersonControls > 
```
which emits 
```
var controls = new FirstPersonControls(camera, domElement);
```
When I try to use `createNew` with `FirstPersonControls.Invoke`, as in your example:
```
let controls = createNew  FirstPersonControls.Invoke (camera :> Three.Camera, domElement) |> unbox< IFirstPersonControls > 
```
the js does not transpile as desired:
```
	    var controls = new function (tupledArg) {
	        return FirstPersonControls(tupledArg[0], tupledArg[1]);
	    }(camera, domElement);
```
Is there a way to use `createNew` with `Func<>` syntax?

**Comment by alfonsogarciacaro** [comment]
True, sorry! 😅 

`createNew` works dynamically, so you don't need to specify the signature:

```fsharp
let FirstPersonControls : obj = importMember "../app/js/FirstPersonControls.js"

let controls: IFirstPersonControls =
    createNew FirstPersonControls (camera :> Three.Camera, domElement) |> unbox
```

**Comment by aolney** [comment]
Beautiful :metal:

**Comment by alfonsogarciacaro** [comment]
In latest alpha (`fable-compiler@next` and `fable-core@next`), I've added `JsCons` to `Fable.Core.JsInterop` to make it easier to import constructors, so you can do:

```fsharp
let FirstPersonControls: JsCons<IFirstPersonControls> =
    importMember "../app/js/FirstPersonControls.js"

// controls will be of type IFirstPersonControls without casting,
// but the constructor arguments are not typed
let controls = FirstPersonControls.Create(camera :> Three.Camera, domElement)
```

Please tell me what you think, whether it's an improved or not over dynamic invocation, if it can still be made more elegant, etc :+1:

**Comment by aolney** [comment]
I like what your proposing above b/c
- It makes the type of `FirstPersonControls` clear at the moment of creation
- no more unboxing
- createNew is a little confusing b/c you have to add white space before the parameters

The only thing I'm not confident of is if `JsCons` is the best name. I don't recall seeing a lot of types with the Js prefix, and Cons might be too short to be immediately understood as constructor. I don't know much js but I wonder if `JsClass` or `Proto` might be alternatives.

Another thought: I like the idea of parity between the dynamic and foreign interface operations. Ideally there would be a 1-to-1 correspondence, and in the documentation the two variants could be shown side by side. 

Would it make sense to have a foreign interface approach that allows this:
```
let FirstPersonControls: JsCons<Three.Camera, Browser.HTMLElement,IFirstPersonControls> =
    importMember "../app/js/FirstPersonControls.js"
````
and enforces type checking on `Create`? Perhaps you've already done this.

**Comment by aolney** [comment]
Very nice! I thought of combining, but using the interface in the generic signature escaped me. Hope to have another sample done this weekend.

Sent from my Sony Xperia™ smartphone


---- Alfonso Garcia-Caro wrote ----


Thanks a lot for the detailed summary. I understand it can be confusing to work with the different import methods, I need to work on the documentation for that.

My recommendation is that in this simple case you combine both. The only interesting part is the IPerlin interface, so you can define that and still use the import expression:

type IPerlin =
    abstract noise: x:float * y:float * z:float -> float

let ImprovedNoise = importMember<unit->IPerlin>("../app/js/ImprovedNoise.js")

let perlin = ImprovedNoise()
let output = perlin.noise(1.4,2.3,3.6)
Browser.console.log(output);

You can also use the ImportAttribute but this is only recommended for auto-generated bindings.

type IPerlin =
    abstract noise: x:float * y:float * z:float -> float


[<Import("ImprovedNoise", "../app/js/ImprovedNoise.js">]
let ImprovedNoise(): IPerlin = jsNative

let perlin = ImprovedNoise()
let output = perlin.noise(1.4,2.3,3.6)
Browser.console.log(output);

Both of these should work :)

Note the way relative import paths are resolved will change in 0.7 (hopefully) for the better. I'll write a blog post about that.

**Comment by alfonsogarciacaro** [comment]
Hmm, I didn't like much the `JsCons` either but prototypes and constructors are actually different things in JS, and if you want to use it as a proper class you need to declare a proper type with FFI like `type [<Import("FirstPersonControls", "../app/js/FirstPersonControls.js")>] FirstPersonControls(camera, el) =`. What about `JsConstructor`? Would that be a bit clearer?

Also, about typing the arguments. The problem is you would then need different definitions of `JsConstructor` depending on the number of generic arguments (as with the new [JsFunc](https://github.com/fable-compiler/Fable/blob/36865448ed5dbb1baa6097c8acd35df857739286/src/fable/Fable.Core/Fable.Core.fs#L163-L193)), which can be a bit cumbersome. But we can try to find a solution :+1:

**Comment by aolney** [comment]
JsConstructor is more clear for sure :)

**Comment by alfonsogarciacaro** [comment]
I just realized that we can use tuples to make the constructor arguments statically typed too. So in latest alpha you can do:

```fsharp
let FirstPersonControls: JsCons<Three.Camera * Browser.HTMLElement, IFirstPersonControls> =
    importMember "../app/js/FirstPersonControls.js"

let controls = FirstPersonControls.Create(camera, domElement)
```

**Comment by aolney** [comment]
Awesome!

**Comment by alfonsogarciacaro** [comment]
@aolney I'm trying to improve the dynamic programming helpers. I still need to properly document everything but, in order to avoid confusion with `Func<_,_,_>`, at the end I decided to add multiple generic arguments to `JsConstructor` and remove the tuple trick. So the sample above with latest fable-compiler and fable-core would be rewritten as:

```fsharp
open Fable.Core.JsInterop

let FirstPersonControls: JsConstructor<Three.Camera, Browser.HTMLElement, IFirstPersonControls> =
    importMember "../app/js/FirstPersonControls.js"

let controls = FirstPersonControls.Create(camera, domElement)
```

If you're using `JsConstructor` in your code, would you mind updating it? Sorry for that!

**Comment by aolney** [comment]
No problem, thanks for being so conscientious :smile: I will start probing my samples to make sure they work with 0.7
