### ISSUE TITLE
MenuItemOptions click property incorrect

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/fable-electron#4]
The MenuItemsOptions click property is incorrect. 

The property has a function signature of: 
`MenuItem -> BrowserWindow -> KeyboardEvent -> unit`
when it should be
`unit -> unit`

I was able to work around this by doing:

```
let mutable tray: Tray option = Option.None

[<Emit("$0")>]
let menuItemOptionsPojo menuItemOptions : MenuItemOptions = jsNative

let show =
    menuItemOptionsPojo
        ({| label = "Open"
            click = 
                fun () -> 
                    match mainWindow with
                    | Some(win) -> win.show()
                    | None -> () |}) 
    |> U2.Case1

let appTray =
    main.Tray.Create("")

main.Menu.buildFromTemplate [| show |]
|> Some
|> appTray.setContextMenu

tray <- Some appTray
```

**Comment by cmeeren** [comment]
Are you sure? The current signature is according to the [Electron docs](https://electronjs.org/docs/api/menu-item).

![image](https://user-images.githubusercontent.com/7766733/64517961-96c5af80-d2f1-11e9-8032-88088da5dfdf.png)

**Comment by Shmew** [comment]
Yeah, that had me confused as well. 

I looked around a lot on the web and never saw anyone set the click property to anything but `unit -> unit`. I just found one blog post published recently that used that function signature, but I never had any success with it. I usually did it like:

```
let show =
    menuItemOptionsPojo
        ({| label = "Open"
            click = 
                fun (_, _, _) -> 
                    match mainWindow with
                    | Some(win) -> win.show()
                    | None -> () |}) 
    |> U2.Case1
```

Which would never fire. At the very least I can confirm that it does accept `unit -> unit`. You can also see them do this in the official docs [here](https://electronjs.org/docs/api/menu#main-process).

![image](https://user-images.githubusercontent.com/11186595/64546895-23bc3900-d2f1-11e9-9ae0-2536671bb242.png)

**Comment by cmeeren** [comment]
Yes, AFAIK in JS you can drop arguments if you don't need them, so even if you have a callback signature like `a -> b -> unit` you can supply `unit -> unit`.

I suggest you post an issue in the Electron repo, to tell them about this possible bug in the docs. If it really is a bug I can fix the signature.

Come to think of it though... I had a similar issue recently where I explicitly had to wrap the callback in `Func`: https://github.com/Zaid-Ajaj/Feliz/issues/27

Could you try that with your callback? I.e., something like:

```f#
let show =
    ({| label = "Open"
            click = 
                Func<_,_,_,_>(fun (_, _, _) -> 
                    match mainWindow with
                    | Some(win) -> win.show()
                    | None -> ()) |}
    |> U2.Case1
```

**Comment by Shmew** [comment]
Yeah it doesn't like that since it's expecting three arguments it treats the System.Func as a single argument of the three required. Unless I'm just doing it wrong. My repo is [public](https://github.com/Shmew/MordhauBuddy) if you want to look at it yourself.

**Comment by cmeeren** [comment]
Oh, right. Try "cheating" by unboxing the `Func` to the correct type: `unbox(fun (_, ...`

**Comment by Shmew** [comment]
I was able to get this to work:

```
let show =
    main.MenuItem.Create
        (jsOptions<MenuItemOptions> (fun o ->
            o.label <- "Open"
            o.click <- 
                unbox(System.Func<_,unit>(fun (_, _, _) ->
                    match mainWindow with
                    | Some(win) -> win.show()
                    | None -> ()
                )))
            )
    |> U2.Case2
```

**Comment by cmeeren** [comment]
Dang. That likely means that any multi-parameter callback in Fable.Electron suffers from the same problem.

**Comment by cmeeren** [comment]
@Zaid-Ajaj or @alfonsogarciacaro do you have any tips on how to write bindings like the below, considering that the code below doesn't work due to currying?

https://github.com/fable-compiler/fable-electron/blob/bcffb111efc02688d936a0c7b2ea80137ef2ba74/src/Fable.Electron/Bindings.fs#L7381

**Comment by MangelMaxime** [comment]
Seems like the "direct" solution is to create an alias `U3<Func<MenuItem, BrowserWindow, KeyBoardEvent, unit>, Func<MenuItem, BrowserWindow, unit>, Func<MenuItem, unit>`.

I know it looks harder to read but should solve the problem. Other solutions probably need something from the compiler itself I guess.

**Comment by cmeeren** [comment]
Will using `Func` force the user to use `Func` explicitly too, or is that handled automatically by F#/Fable?

Regarding `U3`: Given how hard the signature is to read (and the fact that the user must use `U3.CaseX` or `!^`), I think only the most general callback is better, and users can just use `_` for the ignored parameters.

**Comment by Zaid-Ajaj** [comment]
When you use `jsOptions` you limit yourself in how you initialize the properties and you cannot do "postprocessing" internally in the library to hide some ugly js parts. I guess the best way here is to use overloaded click handlers and then cast them to `Func` internally before making the property.

I haven't tested the code below but it goes something like this
```fs
type IMenuItemProperty = interface end 

type MenuItem with 
    static member click (handler: MenuItem -> BrowserWindow -> KeyboardEvent -> unit) : IMenuItemProperty  = 
      !!("click", System.Func<_, _, _, _> handler)
    static member click (handler: MenuItem -> BrowserWindow -> unit) : IMenuItemProperty  = 
      !!("click", System.Func<_, _, _> handler)
    static member create (props: IMenuItemProperty list) = main.MenuItem.Create (!!createObj (!!props))

main.MenuItem.create [
   MenuItem.label "show"
   MenuItem.click (fun item window keyboardEvent -> ())
   MenuItem.click (fun item window -> ())
   MenuItem.click (fun item -> ())
] 
``` 
Of course this property list syntax doesn't always make sense but in case of UI elements (menu items in this case) it would work nicely

**Comment by cmeeren** [comment]
Thanks! Yes, the Electron bindings are currently "very JS".

General note: Suggestions for improvements, and PRs, are welcome! I have very limited capacity at the moment to work on significant changes to this library. Therefore, at the moment, I'm just looking for a quick fix to actually make this work (and for similar other multi-parameter function properties).

**Comment by MangelMaxime** [comment]
> Therefore, at the moment, I'm just looking for a quick fix to actually make this work

To test but then perhaps:

```fs
abstract click: Func<MenuItem, BrowserWindow, KeyboardEvent, unit> with get, set
```

Force the user to provide a `Func<>` construct.

**Comment by cmeeren** [comment]
Come to think of it, would that just be `Action<MenuItem, BrowserWindow, KeyboardEvent>`?

**Comment by cmeeren** [comment]
@Shmew 3.0.0 will be published soon. Please let me know if it's fixed.

**Comment by MangelMaxime** [comment]
I agree with you @cmeeren my position in general is to have a pure bindings. 

And if people needs something more high level, we (or the consumer) can either have an Helpers module or a dedicated package for that.
