### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-electron#6]
I have just updated Fable.Electron to support Electron 9.0. Unfortunately, I am unable to continue prioritizing keeping Fable.Electron up to date with new Electron versions. It's relatively little work, but since I'm not actively using it and since it's relatively simple for anyone to keep it up to date, my motivation for this is exclusively "because I'm that kind of guy who doesn't give up commitments", which means this is one of many small, but regular drains on my energy.

I have added the text below to the readme (quoting it here for reference), where I mention the work involved. Again, it's not much, so I hope someone who is using Fable.Electron is willing to step up.

Let me know if you have questions, if I should add more details to the description/readme, etc.

@alfonsogarciacaro Could a call for maintainers be communicated in relevant channels?

> Maintainer wanted!
> ------------------
> 
> **If you are actively using Fable.Electron or otherwise interested in seeing these bindings being kept up to date, please consider taking over this project!**
> 
> I am not actively using Fable.Electron and will not be able to prioritize keeping it up to date with new Electron releases. I am therefore seeking a new maintainer.
> 
> **Work involved:** The only thing I have been doing so far is using a website scanner (I use Wachete, but use whatever you want) to monitor [https://www.electronjs.org/docs/all](https://www.electronjs.org/docs/all) for changes, and update the bindings accordingly. Minor releases and relevant documentation updates occur at most once a week (often less) and usually involve 15m to an hour of work (including deployment), while major Electron releases may take a several hours.
> 
> This documentation-driven approach is slightly complicated by the fact that the docs may have bugs, i.e. something should be an array but is documented as a single value. Use your best judgement and search the [Electron source code](https://github.com/electron/electron/) if you’re unsure whether the docs are correct.

**Comment by forki** [comment]
if nobody else volunteers - I think I'd adopt it

**Comment by cmeeren** [comment]
That would be awesome, @forki! I don't know whether you want to wait a bit or not. I won't put money on anyone else stepping up. It's fairly niche, after all. 😛 

Are you interested in taking over [cmeeren/fable-elmish-electron-material-ui-demo](https://github.com/cmeeren/fable-elmish-electron-material-ui-demo), too? That's even less work, just updating dependencies every now and then when you feel like it (e.g. for major Electron releases), and fixing any problems that arise. Unless you feel like making something more of it, of course.

If you're not interested, I'll be posting a call for maintainers for that repo, too.

**Comment by cmeeren** [comment]
I can't see anyone else stepping up - do you want to officially take over, @forki?

**Comment by forki** [comment]
Ok let's do this

Christer van der Meeren <notifications@github.com> schrieb am Mi., 3. Juni
2020, 07:15:

**Comment by cmeeren** [comment]
Thanks a lot! You're now a repo admin. Do you want to take over [https://github.com/cmeeren/fable-elmish-electron-material-ui-demo](cmeeren/fable-elmish-electron-material-ui-demo), too? (See above, feel free to decline, then I'll post a call for maintainers there.)

**Comment by forki** [comment]
I wonder if we should move the sample to fable org as well.

Christer van der Meeren <notifications@github.com> schrieb am Mi., 3. Juni
2020, 08:11:

**Comment by cmeeren** [comment]
I'm fine with that, just let me know if you want admin access to the sample repo and you can arrange whatever you want with the Fable org guys.

**Comment by cmeeren** [comment]
Or perhaps let's move it first, to avoid too many URL changes/redirects.

@MangelMaxime (or anyone else relevant), what do you think? Should https://github.com/cmeeren/fable-elmish-electron-material-ui-demo be moved to the Fable org, just like Fable.Electron is?

**Comment by forki** [comment]
Yes please make me admin. And I assume I also need to get nuget push
privileges

Christer van der Meeren <notifications@github.com> schrieb am Mi., 3. Juni
2020, 08:16:

**Comment by cmeeren** [comment]
Sure, what's your GH username?

**Comment by cmeeren** [comment]
Sure, what's your NuGet username?

**Comment by forki** [comment]
https://www.nuget.org/profiles/sforkmann

Am Mi., 3. Juni 2020 um 08:21 Uhr schrieb Christer van der Meeren <
notifications@github.com>:

**Comment by cmeeren** [comment]
@alfonsogarciacaro @et1975 @MangelMaxime @Zaid-Ajaj 

Do you think https://github.com/cmeeren/fable-elmish-electron-material-ui-demo should be part of the Fable org? Personally I don't care; I just need an answer so I know whether to transfer the repo to @forki or to this org.

**Comment by et1975** [comment]
Any member of elmish org can create/move a repo into elmish, but up to you folks.

**Comment by cmeeren** [comment]
Yes, I looking for approval, not action. :)

**Comment by et1975** [comment]
Sorry, I just see "elmish" in the name and assuming it is a layer above fable and thought you might want to move it elmish org instead.

**Comment by MangelMaxime** [comment]
@cmeeren Sorry for the slow answer, we can move it here and consider it the official sample for electron.

**Comment by cmeeren** [comment]
I tried to transfer ownership, but I "don't have permissions to create public repositories for fable-compiler"

**Comment by MangelMaxime** [comment]
@cmeeren Sorry for the delay, I deleted my fork of your repository can you please try again?

**Comment by cmeeren** [comment]
Done

**Comment by MangelMaxime** [comment]
Thank you I did the transform to fable-compiler.

I also invited you in the `fable-electron` team so you can still have write access to the repository if needed.

**Comment by MangelMaxime** [comment]
I am closing this issue as I don't think much more need to be done.

**Comment by cmeeren** [comment]
Thanks! Make sure to give @forki admin access to the transferred repo.
